id = "monokuro-theme"        # ユニークなID（"zed"や"extension"という単語はNG）
name = "Monokuro theme"
version = "0.0.1"
schema_version = 1
authors = ["Namito Kawane <kawanenamito0426@gmail.com>"]
description = "Monokuro is the romanization of the Japanese pronunciation of 'monochrome.' It's a simple black-and-white theme."
repository = ""
